sudo: false
language: node_js
node_js:
- '6'
script:
- npm test
after_success:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage
